# Author: Adam L. Rich
# Date:   July 17, 2012
# Description:
#
#   projecteuler.net
#

# Problem 2
#
#  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#    
#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#  
#  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

F <- NULL
F[1] = 1
F[2] = 2
x <- 2

while(F[x] + F[x - 1] < 4e6L) {
  x <- x + 1
  F[x] <- F[x - 1] + F[x - 2]
}

# Starting with element 2, every third element is even
sum(F[seq(2, x, by = 3)])
